node{
  stage('SCM Checout'){
   
  git 'https://github.com/sidharthvijayakumar/FinalProj/tree/master/github.com/sidharthvijayakumar/FinalProj.git'
  }
  stage('Comiple-Package'){
     def mvnHome = tool name: 'Maven', type: 'maven'
    sh "${mvnHome}/bin/mvn clean"
  }
}
